version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build Started
      - echo Build Complete
artifacts:
  files:
    - '**/*'
